[project]
name = "dbt-snowflake-poc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dbt-core>=1.10.11",
    "dbt-snowflake>=1.10.0",
]
